const syncActions = [
    "TEST_SYNC_ACTION",

    // FILTERS ACTION TYPES
    "INITIALIZE_SELECTED_FILTER_STATE",
    "TOGGLE_FILTER_EXPAND_STATE",
    "HANDLE_FILTER_OPTION_CLICK",
    "UPDATE_SEARCH_TERM"
];

export default syncActions;
